routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',function(){
return view('welcome') ; 	
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::middleware(['auth'])->group(function () {
    Route::resource('companies', 'CompaniesController');
    Route::get('projects/create/{company_id?}', 'ProjectsController@create');
    Route::post('/projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
    Route::resource('projects', 'ProjectsController');
    Route::resource('roles', 'RolesController');
    Route::resource('users', 'UsersController'); 
    Route::resource('comments', 'CommentsController'); 
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 
        'email', 
        'password',
        'first_name',
        'middle_name',
        'last_name',
        'city',
        'role_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

 public function comments(){
    return $this->hasMany('App\Comment');
 }
 public function role(){
    return $this->belongsTo('App\Role');
 }
 public function companies(){
    return $this->hasMany('App\Company');
 }
 
 
  public function projects()
  {
    return $this->belongsToMany('App\Project');
 }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
          if(Auth::check()){
         $users = User::where('id', Auth::user()->id)->get();
          return view('users.index', ['users' => $users]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')



     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left " style="background: white;">
    <h1>Créer un nouveau projet </h1>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" >

      <form method="post" action="{{ route('projects.store') }}">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <label for="project-name">Nom<span class="required">*</span></label>
                                <input   placeholder="Entrer le nom"  
                                          id="project-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                           />
                            </div>
                              @if($companies == null)
                              <input   class="form-control" type="hidden" name="company_id" value="{{ $company_id }}" />
                               @endif
                                 @if($companies != null)
                                <div class="form-group">
                                <label for="company-content">Choisir l'entreprise</label>

                                <select name="company_id" class="form-control"> 
                                @foreach($companies as $company)
                                        <option value="{{$company->id}}"> {{$company->name}} </option>
                                      @endforeach
                                </select>
                            </div>
                            @endif
                            <div class="form-group">
                                <label for="project-content">Description</label>
                                <textarea placeholder="Entrer la description" 
                                          style="resize: vertical" 
                                          id="project-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Envoyer"/>
                            </div>
                        </form>
   

      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects"> <i class="fa fa-building-o" aria-hidden="true"></i> La liste des projets</a></li>
              
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
        </div>


    @endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')


     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left ">
       
      

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px; ">
     <form method="post" action="{{ route('companies.update',[$company->id]) }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="_method" value="put">

                            <div class="form-group">
                                <label for="company-name">Nom<span class="required">*</span></label>
                                <input   placeholder="Enter le nom"  
                                          id="company-name"
                                          required
                                          name="name"
                                          spellcheck="false"
                                          class="form-control"
                                          value="{{ $company->name }}"
                                           />
                            </div>


                            <div class="form-group">
                                <label for="company-content">Description</label>
                                <textarea placeholder="Entrer la description" 
                                          style="resize: vertical" 
                                          id="company-content"
                                          name="description"
                                          rows="5" spellcheck="false"
                                          class="form-control autosize-target text-left">
                                          {{ $company->description }}</textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Envoyer"/>
                            </div>
                        </form>
    
      </div>
</div>


<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/companies/{{ $company->id }}">la liste des entreprises</a></li>
              <li><a href="/companies">Tout les entreprises</a></li>
             
            
            <br/>
            
            
              <li>

                  
              <a   
              href="#"
                  onclick="
                  var result = confirm('Are you sure you wish to delete this Company?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }
                          "
                          >
                  Supprimer
              </a>

              <form id="delete-form" action="{{ route('companies.destroy',[$company->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>

 
              
              
              </li>

              <!-- <li><a href="#">Ajouter un nouveau membre</a></li> -->
            </ol>
          </div>

          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->
        </div>


    @endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
<div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
<div class="panel panel-primary">
  <div class="panel-heading">Les utilisateurs</div>
  
  <div class="panel-body">

    <ul class="list-group">
      @foreach($users as $user)
  <li class="list-group-item"> <a href="/users/{{$user->id}}">{{$user->name}} :  {{$user->email}}
  </a></li>
      @endforeach
</ul>
  </div>
</div>
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
     
     <div class="row col-md-9 col-lg-9 col-sm-9 pull-left ">
      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <!-- Jumbotron -->
      <div class="well well-lg" >
        <h1>{{ $project->name }}</h1>
        <p class="lead">{{ $project->description }}</p>
       <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
      </div>

      <!-- Example row of columns -->
      <div class="row  col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px; ">
       <!--<a href="/projects/create/{{ $project->id }}" class="pull-right btn btn-default btn-sm" >Ajouter un projet</a>-->
      <br>
@include('partials.comments')
     <div class="row container-fluid">

<form method="post" action="{{ route('comments.store') }}">
                            {{ csrf_field() }}


                          <input type="hidden" name="commentable_type" value="App\Project">
                            <input type="hidden" name="commentable_id" value="{{$project->id}}">

                            <div class="form-group">
                                <label for="comment-content">Commentaire</label>
                                <textarea placeholder="Entrer commentaire" 
                                          style="resize: vertical" 
                                          id="comment-content"
                                          name="body"
                                          rows="3" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>

                            
                            <div class="form-group">
                                <label for="comment-content">Preuve de votre travail(lien)</label>
                                <textarea placeholder="Enter url or screenshots" 
                                          style="resize: vertical" 
                                          id="comment-content"
                                          name="url"
                                          rows="2" spellcheck="false"
                                          class="form-control autosize-target text-left">

                                          
                                          </textarea>
                            </div>


                            <div class="form-group">
                                <input type="submit" class="btn btn-primary"
                                       value="Envoyer"/>
                            </div>
                        </form>
   


                        </div>

                 <!--@foreach($project->comments as $comment)
        <div class="col-lg-4 col-md-4 col-sm-4">
          <h2>{{ $comment->body }}</h2>
          <p class="text-danger"> {{$comment->url}} </p>
          <p><a class="btn btn-primary" href="/projects/{{ $project->id }}" role="button"> Voir Projet »</a></p>
        </div>
      @endforeach
      </div>-->
     

      </div> 
</div>
<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
          <!--<div class="sidebar-module sidebar-module-inset">
            <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
          </div> -->
          <div class="sidebar-module">
            <h4>Actions</h4>
            <ol class="list-unstyled">
              <li><a href="/projects/{{ $project->id }}/edit"> <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Modifier un projet</a></li>
              <li><a href="/projects"><i class="fa fa-user-o" aria-hidden="true"></i> Mes projets</a></li>
              <li><a href="/project/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Créer une nouveau projet</a></li>
               @if($project->user_id == Auth::user()->id)
              <li>
              <i class="fa fa-power-off" aria-hidden="true"></i>   
              <a   
              href="#"
                  onclick="
                  var result = confirm('Vous voulez vraiment supprimer ce projet?');
                      if( result ){
                              event.preventDefault();
                              document.getElementById('delete-form').submit();
                      }">
                  Supprimer
              </a>
              <form id="delete-form" action="{{ route('projects.destroy',[$project->id]) }}" 
                method="POST" style="display: none;">
                        <input type="hidden" name="_method" value="delete">
                        {{ csrf_field() }}
              </form>
            </div>
              </li>
          @endif
              <!-- <li><a href="#">Ajouter un nouveau membre</a></li> -->
            </ol>
            <hr/>
         <h4>Ajouter des membres</h4>
<div class="row">
              <div class="col-lg-12 col-md-12 col-xs-12  col-sm-12 ">
               <form id="add-user" action="{{ route('projects.adduser') }}" 
                method="POST">
                {{ csrf_field() }}
                <div class="input-group"> 
                  
                  <input class="form-control" placeholder="Email" type="text" name="email" >
                  <input class="form-control" type="hidden" value="{{$project->id}}" name="project_id">
                  <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="addMember" >Ajouter</button>
                  </span>
                </div><!-- /input-group -->
                </form>
              </div><!-- /.col-lg-6 -->
            </div><!-- /.row -->
            <br/>
             <h4>membres de l'équipe</h4>
            <ol class="list-unstyled">
              @foreach($project->users as $user)
              <li><a href="#">{{$user->email}}</a></li>
              @endforeach
              
            </ol>
          <!--<div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
              <li><a href="#">March 2014</a></li>
            </ol>
          </div> -->

        </div>


    @endsection